# Dependabot disabled (user request on 2025-08-14).
# Keeping file (commented) so it can be easily reinstated later.
# To re-enable, restore original YAML (remove comment markers) and commit.
#
# Original config:
# version: 2
# updates:
# - package-ecosystem: "bundler"
#   directory: "/"
#   schedule:
#     interval: "weekly"
#   open-pull-requests-limit: 5
#   allow:
#   - dependency-type: "all"
#   labels:
#   - "dependencies"
#   - "security"
# - package-ecosystem: "github-actions"
#   directory: "/"
#   schedule:
#     interval: "weekly"
#   open-pull-requests-limit: 5
#   labels:
#   - "dependencies"
#   - "ci"
