config:
  # Disable line length (handled intentionally for tables / code) and inline HTML warnings
  MD013: false
  MD033: false
  # Duplicate heading rule: keep default; disabling entirely would hide genuine issues
  # (No custom properties; previous allow_different_nesting removed as unsupported.)
  # Require consistent ATX style
  MD003:
    style: atx
  # Trailing spaces disallowed (strict true enforces removal)
  MD009:
    strict: true
  # Lists should be consistent (dash style)
  MD004:
    style: dash

globs:
  - "README.md"
  - "docs/**/*.md"
  - "_posts/**/*.md"
  - "AGENTS.MD"

ignores:
  - "_site/"
  - "vendor/"
