### CI Lite Overrides
# Exclude bulky experimental data & embedded virtual environment to prevent early memory termination.
exclude:
- _data/Swiss-Folklore-Work-in-Progress/**
- _data/Swiss-Folklore-Work-in-Progress
- _data/Checkins/**
- _data/Checkins

# (Optional) add other heavy paths if needed later.

### Note
# Full build (including these paths) still occurs locally or if CI_DEBUG_FULL=1 is set (we will conditionally override in workflow).
