name: UX Issue
description: Template for reporting or suggesting UX improvements.
title: "XX-###: [Short Title of UX Issue]"
labels: ["UX", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        <!-- ========================================= -->
        <!--  UX-XXX : [Short Title of UX Issue] -->
        <!-- ========================================= -->
  - type: dropdown
    id: type
    attributes:
      label: Type
      description: Select the type of UX issue.
      options:
        - Enhancement
        - Feature Request
        - Other
    validations:
      required: true
  - type: input
    id: summary
    attributes:
      label: Summary
      description: Briefly describe the UX issue or improvement.
      placeholder: e.g. Raise baseline font size, tighten line-length, and adjust line-height for readability.
    validations:
      required: true
  - type: textarea
    id: user-story
    attributes:
      label: User Story
      description: "Use the format: As a [type of user], I want [what the user wants], so that [the benefit or value]."
      placeholder: As a [type of user], I want [what the user wants], so that [the benefit or value].
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: List the criteria that must be met for this issue to be considered complete.
      placeholder: |
        - [ ] [Criterion 1]
        - [ ] [Criterion 2]
        - [ ] [Criterion 3]
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - High
        - Medium
        - Low
    validations:
      required: true
