---
layout: GammaWorld
date: '2023-01-04T23:10:05.552Z'
title: Waldis
GenericName: ''
Name: Waldis
Common_Name: Sage of Melkath
Other_Names: ''
Generic_Name: ''
Source: GW07 Module
Author: Bruce Nesmith
MCC Race: 'PSH: Sentinel'
Role_In_Gamma_World: NPC
Number_Appearing_Dice: '1'
Morale: '12'
Hit_Dice: '12'
Armor: '8'
Control: ''
Sensors: ''
Power: ''
Land_Speed: '48'
Air_Speed: ''
Water_Speed: ''
Burrowing_Speed: ''
Climbing_Speed: ''
Wheeled_Speed: ''
Tread_Speed: ''
Rotors_Speed: ''
Hoverfan_Speed: ''
Gav_Pod_Speed: ''
PS: '9'
DX: '10'
CN: '14'
MS: '11'
CH: '17'
IN: '21'
Brain Type / CPU: ''
Attack_1: ''
Attack_2: ''
Attack_3: ''
Mutations: None
Size: ''
Size_Measurement: ''
Frequency: ''
Organization: ''
Activity_Cycle: ''
Diet: ''
Tech_Level: ''
Tech_Max: ''
Artifacts: ''
Habitat: ''
Base_Stock: ''
Robot_Classification: ''
Status: ''
Mission: ''
Description: ''
Equipment: ''
Reactions: ''
Behavior: ''
Repair_and_Healing: ''
New_Description: ''
Combat: ''
Society: ''
Brotherhood_of_Thought: ''
Restorationsist: ''
Healers: ''
Iron_Society: ''
Humans: ''
Monster_Name: Waldis 'Sage of Melkath'
Number_appearing: '1'
Number_appearing_Single: '1'
Init: '+2'
Monster_Name_xx_number_if_applicable_Init_+-x: "Waldis 'Sage of Melkath' (1): Init\
  \ +2"
PS_-_C: '9'
DX_-_C: '10'
CN_-_C: '14'
MS_-_C: '11'
CH_-_C: '17'
IN_-_C: '21'
Weapon: Low Tech Level
Plus_to_hit_and_damage_Range_from_Stats: '0'
Plus_to_Range_from_Level: ''
Plus_to_Range: '2'
Plus_to_hit_and_damage_Melee_From_Stats: '0'
Plus_to_Melee_from_Level: ''
Plus_to_Melee: '2'
Plus_to_Generic_Attack_from_Level: '2'
Attack_1_Number_of_Attacks: ''
Attack_1_Attack_Name: ''
Attack_1_Type: ''
Attack_1_Range: ''
Attack_1_Attack_Dice: ''
Attack_1_Bonus_to_Hit: ''
Attack_1_Bonus_to_Damage: ''
New_Attack_1: See Description
Attack_2_Number_of_Attacks: ''
Attack_2_Attack_Name: ''
Attack_2_Type: ''
Attack_2_Range: ''
Attack_2_Attack_Dice: ''
Attack_2_Bonus_to_Hit: ''
Attack_2_Bonus_to_Damage: ''
New_Attack_2: ''
Attack_3_Number_of_Attacks: ''
Attack_3_Attack_Name: ''
Attack_3_Type: ''
Attack_3_Range: ''
Attack_3_Attack_Dice: ''
Attack_3_Bonus_to_Hit: ''
Attack_3_Bonus_to_Damage: ''
New_Attack_3: ''
Atk_weapon_+-x_melee_xdx_andor_weapon_+-x_missile_fire_xdx_range: atk see description
AC_xx: AC 18
Effective_Class_Level: '2'
New_Level: '4'
New_Hit_Dice: HD 4D12
New_HD_xdx_plus_minus: HD 4D12
New_hp_xx_or_hp_xx_each_or_hp_xx_xx_xx: hp 26
New_Hit_Points: '26'
D6_Hitdice: '12'
Total_GW_hit_points_plus_Constant: '72'
MV_xx: MV 60'
Walk: 60'
Fly: ''
Swim: ''
Burrow: ''
Climb: ''
Wheels: ''
Treads: ''
Rotors: ''
Hoverfans: ''
GravPods: ''
New_Action_Dice: 1d20
SV_Fort_+-x_Ref_+-x_Will_+-x: SV Fort +1, Ref +0, Will +0
Fort_Save: '1'
Ref_Save: '0'
Will: '0'
Normal_Text: "Waldis 'Sage of Melkath' (1): Init +2; atk see description; AC 18; HD\
  \ 4D12 hp 26; MV 60' ; 1d20; SV Fort +1, Ref +0, Will +0"
...
