---
layout: GammaWorld
date: '2023-01-04T23:10:05.541Z'
title: Jonn Dukas
GenericName: ''
Name: Jonn Dukas
Common_Name: ''
Other_Names: ''
Generic_Name: ''
Source: GW08 Module
Author: Kim Eastland
MCC Race: 'PSH: Sentinel'
Role_In_Gamma_World: NPC
Number_Appearing_Dice: ''
Morale: ''
Hit_Dice: ''
Armor: ''
Control: ''
Sensors: ''
Power: ''
Land_Speed: ''
Air_Speed: ''
Water_Speed: ''
Burrowing_Speed: ''
Climbing_Speed: ''
Wheeled_Speed: ''
Tread_Speed: ''
Rotors_Speed: ''
Hoverfan_Speed: ''
Gav_Pod_Speed: ''
PS: ''
DX: ''
CN: ''
MS: ''
CH: ''
IN: ''
Brain Type / CPU: ''
Attack_1: ''
Attack_2: ''
Attack_3: ''
Mutations: ''
Size: ''
Size_Measurement: ''
Frequency: ''
Organization: ''
Activity_Cycle: ''
Diet: ''
Tech_Level: ''
Tech_Max: ''
Artifacts: ''
Habitat: ''
Base_Stock: Human
Robot_Classification: ''
Status: ''
Mission: ''
Description: ''
Equipment: ''
Reactions: ''
Behavior: ''
Repair_and_Healing: ''
New_Description: ''
Combat: ''
Society: ''
Brotherhood_of_Thought: ''
Restorationsist: ''
Healers: ''
Iron_Society: ''
Humans: ''
Monster_Name: Jonn Dukas
Number_appearing: '1'
Number_appearing_Single: ''
Init: '-3'
Monster_Name_xx_number_if_applicable_Init_+-x: 'Jonn Dukas (1): Init -3'
PS_-_C: ''
DX_-_C: ''
CN_-_C: ''
MS_-_C: ''
CH_-_C: ''
IN_-_C: ''
Weapon: Low Tech Level
Plus_to_hit_and_damage_Range_from_Stats: '-3'
Plus_to_Range_from_Level: ''
Plus_to_Range: '-2'
Plus_to_hit_and_damage_Melee_From_Stats: '-3'
Plus_to_Melee_from_Level: ''
Plus_to_Melee: '-2'
Plus_to_Generic_Attack_from_Level: '1'
Attack_1_Number_of_Attacks: ''
Attack_1_Attack_Name: ''
Attack_1_Type: ''
Attack_1_Range: ''
Attack_1_Attack_Dice: ''
Attack_1_Bonus_to_Hit: ''
Attack_1_Bonus_to_Damage: ''
New_Attack_1: See Description
Attack_2_Number_of_Attacks: ''
Attack_2_Attack_Name: ''
Attack_2_Type: ''
Attack_2_Range: ''
Attack_2_Attack_Dice: ''
Attack_2_Bonus_to_Hit: ''
Attack_2_Bonus_to_Damage: ''
New_Attack_2: ''
Attack_3_Number_of_Attacks: ''
Attack_3_Attack_Name: ''
Attack_3_Type: ''
Attack_3_Range: ''
Attack_3_Attack_Dice: ''
Attack_3_Bonus_to_Hit: ''
Attack_3_Bonus_to_Damage: ''
New_Attack_3: ''
Atk_weapon_+-x_melee_xdx_andor_weapon_+-x_missile_fire_xdx_range: atk see description
AC_xx: AC 10
Effective_Class_Level: '1'
New_Level: '1'
New_Hit_Dice: HD 1D12
New_HD_xdx_plus_minus: HD 1D12
New_hp_xx_or_hp_xx_each_or_hp_xx_xx_xx: hp 7
New_Hit_Points: '7'
D6_Hitdice: ''
Total_GW_hit_points_plus_Constant: '0'
MV_xx: NO MOVEMENT
Walk: ''
Fly: ''
Swim: ''
Burrow: ''
Climb: ''
Wheels: ''
Treads: ''
Rotors: ''
Hoverfans: ''
GravPods: ''
New_Action_Dice: 1d20
SV_Fort_+-x_Ref_+-x_Will_+-x: SV Fort -3, Ref -3, Will -3
Fort_Save: '-3'
Ref_Save: '-3'
Will: '-3'
Normal_Text: 'Jonn Dukas (1): Init -3; atk see description; AC 10; HD 1D12 hp 7; NO
  MOVEMENT; 1d20; SV Fort -3, Ref -3, Will -3'
...
