import { test } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import * as fs from 'fs';
import * as path from 'path';

type RepresentativePage = {
  label: string;
  route: string;
};

type ViolationSummary = {
  id: string;
  impact: string;
  help: string;
  helpUrl: string;
  affectedNodes: number;
  targets: string[];
};

type PageSummary = {
  label: string;
  route: string;
  blockingViolationCount: number;
  blockingViolations: ViolationSummary[];
};

const representativePages: RepresentativePage[] = [
  { label: 'Homepage', route: '/' },
  { label: 'Prompt Library', route: '/prompts/' },
  { label: 'Prompt Details', route: '/prompts/business-case-and-requirements-assistant/' },
  { label: 'Profile', route: '/profile/' },
  { label: 'Category Archive', route: '/category/Prompts.html' },
  { label: 'Long-form Article', route: '/Swiss-Folklore/The-Basilisk-Egg/' }
];

const blockingImpacts = new Set(['serious', 'critical']);
const pageSummaries: PageSummary[] = [];
const reportsDir = path.join(process.cwd(), 'reports', 'accessibility');
const jsonReportPath = path.join(reportsDir, 'site-baseline.json');
const markdownReportPath = path.join(reportsDir, 'site-baseline.md');

function summarizeTargets(targets: string[][]): string[] {
  return targets
    .map(target => target.join(' > '))
    .slice(0, 5);
}

function buildMarkdownReport(summaries: PageSummary[]): string {
  const violationRollup = new Map<string, { count: number; pages: Set<string>; help: string; helpUrl: string; impact: string }>();

  for (const summary of summaries) {
    for (const violation of summary.blockingViolations) {
      const existing = violationRollup.get(violation.id);
      if (existing) {
        existing.count += violation.affectedNodes;
        existing.pages.add(summary.route);
      } else {
        violationRollup.set(violation.id, {
          count: violation.affectedNodes,
          pages: new Set([summary.route]),
          help: violation.help,
          helpUrl: violation.helpUrl,
          impact: violation.impact
        });
      }
    }
  }

  const prioritizedGaps = Array.from(violationRollup.entries())
    .sort((a, b) => b[1].count - a[1].count)
    .map(([id, data]) => {
      const pages = Array.from(data.pages).sort().join(', ');
      return `- ${id} (${data.impact}): ${data.help}. Affected nodes: ${data.count}. Pages: ${pages}. Reference: ${data.helpUrl}`;
    });

  const pageLines = summaries.map(summary => {
    if (summary.blockingViolations.length === 0) {
      return `- ${summary.label} (${summary.route}): no serious or critical axe violations in the latest run.`;
    }

    const rules = summary.blockingViolations
      .map(violation => `${violation.id} (${violation.affectedNodes})`)
      .join(', ');

    return `- ${summary.label} (${summary.route}): ${summary.blockingViolationCount} serious/critical findings across ${summary.blockingViolations.length} rule(s): ${rules}.`;
  });

  return [
    '# Accessibility Baseline Report',
    '',
    'Generated by `npm run test:a11y:baseline`.',
    '',
    '## Representative Pages',
    '',
    ...representativePages.map(page => `- ${page.label}: ${page.route}`),
    '',
    '## Latest Results',
    '',
    ...pageLines,
    '',
    '## Prioritized Remaining Gaps',
    '',
    ...(prioritizedGaps.length > 0 ? prioritizedGaps : ['- No serious or critical axe violations were detected in this run.']),
    ''
  ].join('\n');
}

test.describe.serial('Site accessibility baseline', () => {
  for (const representativePage of representativePages) {
    test(`audit ${representativePage.label}`, async ({ page }) => {
      await page.goto(representativePage.route, { waitUntil: 'domcontentloaded' });
      await page.waitForTimeout(1000);

      const results = await new AxeBuilder({ page })
        .withTags(['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa'])
        .analyze();

      const blockingViolations = results.violations
        .filter(violation => blockingImpacts.has(violation.impact || ''))
        .map(violation => ({
          id: violation.id,
          impact: violation.impact || 'unknown',
          help: violation.help,
          helpUrl: violation.helpUrl,
          affectedNodes: violation.nodes.length,
          targets: summarizeTargets(violation.nodes.map(node => node.target))
        }));

      pageSummaries.push({
        label: representativePage.label,
        route: representativePage.route,
        blockingViolationCount: blockingViolations.reduce((sum, violation) => sum + violation.affectedNodes, 0),
        blockingViolations
      });

      if (blockingViolations.length > 0) {
        console.log(`\n[a11y-baseline] ${representativePage.label} (${representativePage.route})`);
        for (const violation of blockingViolations) {
          console.log(`- ${violation.id} (${violation.impact}) nodes=${violation.affectedNodes}`);
          console.log(`  ${violation.helpUrl}`);
          for (const target of violation.targets) {
            console.log(`  target: ${target}`);
          }
        }
      }
    });
  }

  test.afterAll(async () => {
    fs.mkdirSync(reportsDir, { recursive: true });
    fs.writeFileSync(jsonReportPath, JSON.stringify(pageSummaries, null, 2));
    fs.writeFileSync(markdownReportPath, buildMarkdownReport(pageSummaries));
  });
});