name: Build and Validate

on:
  push:
  pull_request:

jobs:
  build-validate:
    runs-on: ubuntu-latest
    env:
      RUBYOPT: -rdate
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: false
      - name: Cache vendor/bundle
        uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: gems-${{ runner.os }}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            gems-${{ runner.os }}-
      - name: Add Linux platform to lockfile
        run: |
          ruby -v
          bundler -v
          bundle lock --add-platform x86_64-linux || true
          bundle lock --add-platform ruby || true
      - name: Install Gems
        run: bundle install --jobs 4 --path vendor/bundle
      - name: Security Audit (bundler-audit)
        run: |
          bundle exec bundler-audit update
          bundle exec bundler-audit check || (echo 'Vulnerable gems found'; exit 1)
      - name: Backup post file check
        run: ruby tests/check_no_backup_posts.rb
      - name: Build Jekyll
        run: bundle exec jekyll build --quiet
      - name: Legacy key check
        run: ruby tests/check_no_legacy_siteurl.rb
      - name: Normalize Dates (microsecond timestamps)
        run: ruby _code/normalize_dates.rb
      - name: Feed integrity
        run: ruby tests/check_feed_integrity.rb
      - name: HTML Proofer (links & images)
        run: |
          set -o pipefail
          mkdir -p logs
          TS=$(date -u +"%Y-%m-%dT%H-%M-%S")
          LOG_FILE="logs/${TS}-HTML-Logging.txt"
          echo "Saving HTML Proofer output to $LOG_FILE" 
          # Run htmlproofer, tee output to log file, preserve exit code
          bundle exec htmlproofer ./_site --check-html --allow-missing-href 2>&1 | tee "$LOG_FILE"
          EXIT_CODE=${PIPESTATUS[0]}
          if [ $EXIT_CODE -ne 0 ]; then
            echo 'HTML Proofer issues found';
            exit $EXIT_CODE;
          fi
      - name: Upload HTML Proofer Log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: html-proofer-logs
          path: logs/*-HTML-Logging.txt
      - name: Validate Mastodon Feed
        run: ruby tests/validate_mastodon_feed.rb
      - name: Mastodon toot length stats (informational)
        run: ruby tests/report_mastodon_feed_lengths.rb
      - name: Image Path Audit
        run: |
          ruby tests/check_image_paths.rb || true
      - name: Image Alt Text Safety
        run: |
          ruby tests/check_image_alt_text.rb
      - name: Fail if feed invalid (marker file)
        run: |
          if [ ! -f _site/feed-mastodon.json ]; then echo "Missing mastodon feed"; exit 1; fi
      - name: Sitemap Freshness
        run: ruby tests/check_sitemap_freshness.rb
