# For most projects, this workflow file will not need changing; you simply need
# to commit it to your repository.
#
# You may wish to alter this file to override the set of languages analyzed,
# or to provide custom queries or build logic.
#
# ******** NOTE ********
# We have attempted to detect the languages in your repository. Please check
# the `language` matrix defined below to confirm you have the correct set of
# supported CodeQL languages.
#
name: "CodeQL Advanced"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '30 9 * * 4'

jobs:
  analyze:
    name: CodeQL (Ruby / JS / Python)
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      packages: read
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python (for scripts)
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ruby,javascript-typescript,python
          config-file: ./.github/codeql/codeql-config.yml
          trap-caching: false # avoid cache key contention seen previously
          build-mode: none

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/codeql"