name: "[FAST] Quick Build & Lint"

on:
  push:
    branches-ignore:
      - main  # main still uses full CI; remove this line if you want fast CI on main too
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  fast-validate:
    runs-on: ubuntu-latest
    timeout-minutes: 8
    env:
      RUBYOPT: -rdate
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Install Gems (cached)
        run: |
          bundle install --jobs 4 --path vendor/bundle

      - name: Fast Jekyll Build (incremental disabled for determinism)
        run: |
          bundle exec jekyll build --quiet || (echo 'Jekyll build failed'; exit 1)

      - name: Core feed + sitemap sanity
        run: |
          test -f _site/feed.json || (echo 'Missing feed.json'; exit 1)
          test -f _site/sitemap.xml || (echo 'Missing sitemap.xml'; exit 1)

      - name: Spot check for backup files
        run: ruby tests/check_no_backup_posts.rb

      - name: Light HTML spot check (index only)
        run: |
          if [ -f _site/index.html ]; then
            grep -qi '<html' _site/index.html || (echo 'index.html missing <html>'; exit 1)
          else
            echo 'index.html missing from build output'; exit 1
          fi

      - name: Summary
        run: |
          echo "### Fast CI Summary" >> $GITHUB_STEP_SUMMARY
          echo "Build completed: $(date -u +%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_STEP_SUMMARY
          echo "Site size: $(du -sh _site 2>/dev/null | cut -f1)" >> $GITHUB_STEP_SUMMARY

    # Notes:
    # - Excludes: bundler-audit, htmlproofer, full feed integrity tests, image audits, mastodon feed validation, sitemap freshness, memory profiling
    # - Kept: build, minimal structural checks, backup file guard
    # - Adjust branches-ignore above if you want this to run on main alongside full CI
