name: Feed → Mastodon
on:
  push:            # run every time you publish
    branches: [main]
  schedule:        # …or on a cron if you prefer
    - cron: "0 */6 * * *"
jobs:
  toot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Post new items
        uses: nhoizey/github-action-feed-to-mastodon@v2
        with:
          feedUrl:      "https://tedt.org/feed.json"
          mastodonInstance: "https://mastodon.social"   # your home
          mastodonToken:  ${{ secrets.MASTODON_TOKEN }}
