name: Feed 2 Mastodon

permissions:
  contents: write

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch: {}

jobs:
  toot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Decide if we should post (latest already tooted?)
        id: guard
        run: |
          python3 _code/should_post_latest.py > guard.json || true
          echo "Guard output:" && cat guard.json || true
          SHOULD=$(python3 -c "import json;print(json.load(open('guard.json')).get('should_post','false'))" || echo false)
          echo "should_post=$SHOULD" >> $GITHUB_OUTPUT

      - name: Pull latest (ensure cache freshness)
        run: git pull --ff-only || true

      - name: Normalize Mastodon cache
        id: normalize-cache
        run: |
          python3 _code/normalize_masto_cache.py || true

      - name: Post new items
        id: feed2mastodon
        if: steps.guard.outputs.should_post == 'true'
        uses: nhoizey/github-action-feed-to-mastodon@v2
        with:
          feedUrl: "https://tedt.org/feed-mastodon.json"
          mastodonInstance: "https://tschopp.net"
          mastodonToken: ${{ secrets.MASTODON_TOKEN }}
          # During first normalized run, suppress reposting by honoring script output
          ignoreFirstRun: ${{ steps.normalize-cache.outputs.ignore_first_run || 'false' }}
          itemChoiceStrategy: newest
          globalDelayToots: 60
          delayTootsSameItem: 2880

      - name: Skip note
        if: steps.guard.outputs.should_post != 'true'
        run: |
          echo "Skipping feed-to-mastodon: latest post already has mastodon-post-id."

      - name: Resolve canonical path for toot
        if: steps.feed2mastodon.outputs.tootUrl
        id: resolve-canonical
        env:
          TOOT_URL: ${{ steps.feed2mastodon.outputs.tootUrl }}
        run: |
          python3 _code/resolve_canonical_path.py > /dev/null || true

      - name: Update mastodon-post-id in source markdown
        if: steps.feed2mastodon.outputs.tootUrl
        id: update-frontmatter
        env:
          TOOT_URL: ${{ steps.feed2mastodon.outputs.tootUrl }}
          ITEM_URL: ''
          ITEM_ID: ${{ steps.resolve-canonical.outputs.CANONICAL_PATH || '' }}
        run: |
          python3 _code/update_masto_frontmatter.py || true

      - name: Commit and push cache & updated post
        if: always()
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "chore: update Mastodon cache & post front matter"
          file_pattern: cache/*.json _posts/**/*.md

      - name: Show toot URL
        if: steps.feed2mastodon.outputs.tootUrl
        run: |
          echo "Toot created: ${{ steps.feed2mastodon.outputs.tootUrl }}"

  scripts-test:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'schedule' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run script sanity tests
        run: |
          python3 tests/_code/test_scripts.py
