name: Playwright Accessibility & Navbar Regression

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Install Ruby gems
        run: bundle install --jobs 4 --retry 3

      - name: Build Jekyll site
        env:
          JEKYLL_ENV: production
        run: bundle exec jekyll build --quiet

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Node dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Run Playwright Tests (Prod Build Served)
        env:
          PLAYWRIGHT_BASE_URL: https://tedt.org
          NO_JEKYLL: '1'
        run: npx playwright test tests/a11y/navbar-regression.spec.ts --reporter=line

      - name: Upload Playwright Artifacts (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-artifacts
          path: playwright-report
          if-no-files-found: ignore
