name: Security Audit

on:
  schedule:
    - cron: '0 5 * * 1'
  workflow_dispatch:

jobs:
  bundler-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: false
      - name: Install dependencies
        run: bundle install --jobs 4 --path vendor/bundle
      - name: Update vulnerability DB
        run: bundle exec bundler-audit update
      - name: Run bundler-audit
        run: bundle exec bundler-audit check --verbose
